<template>
  <v-container fluid>
    <v-row>
      <v-col>
        <h1>Kelola Member</h1>
      </v-col>
    </v-row>
    <v-row>
      <v-col>
        <v-table
          height="70vh"
          fixed-header
          width="50vh"
        >
          <thead>
            <tr>
              <th>Nama</th>
              <th>Email</th>
              <th>Last Online</th>
              <th>Status Verifikasi</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Alviana</td>
              <td>alviana.hermawati1261@gmail.com</td>
              <td>Date</td>
              <td>
                <v-btn
                  color="primary"
                >
                  VERIFIKASI
                </v-btn>
              </td>
            </tr>
            <tr>
              <td>Alviana</td>
              <td>alviana.hermawati1261@gmail.com</td>
              <td>Date</td>
              <td>
                <v-chip
                  color="success"
                  prepend-icon="mdi-check"
                >
                  TERVERIFIKASI
                </v-chip>
              </td>
            </tr>
          </tbody>
        </v-table>
      </v-col>
    </v-row>
  </v-container>
</template>
