runtime: php81
service: e-nyileh--api
entrypoint: serve public/index.php
instance_class: F1
automatic_scaling:
  max_instances: 2
env_variables:
  APP_ENV: production
  APP_DEBUG: false

  # Please set DB environment variables in .env files

  CACHE_DRIVER: database
  FILESYSTEM_DISK: gcs
  SESSION_DRIVER: database

  MEDIA_DISK: gcs
  MEDIA_PREFIX: user-contents

